'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Poppins } from 'next/font/google'
import './globals.css'
import NavbarComponent from './components/navbar/navbar'
import { usePathname } from 'next/navigation'



const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({
  subsets: ['latin'],
  weight: '400'
});


/* export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname();
  return (
    <html lang="es">
      
      <body className={`${poppins.className} relative`} >
        {<NavbarComponent></NavbarComponent>}
        {children}</body>
    </html>
  )
}
